name: Publish
on:
  push:
    tags:
      - "v*"
    strategy:
      matrix:
        python-version: ["3.13"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dev/test dependencies
        run: |
          pip install -e ".[dev]"
          pip install -e ".[test]"

      - name: Run tests
        run: |
          make check

  publish:
    needs: test
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Update version from tag
        run: |
          # Strip 'v' prefix from tag and update version.py
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "__version__ = \"${VERSION}\"" > src/mcp_text_editor/version.py

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Build package
        run: |
          uv build

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv publish --token $PYPI_TOKEN
